language: java
os: linux
dist: trusty
jdk: oraclejdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    on_success: never